--- (168)OnAbilityEndChannel
MODIFIER_EVENT_ON_ABILITY_END_CHANNEL
--- (165)OnAbilityExecuted
MODIFIER_EVENT_ON_ABILITY_EXECUTED
--- (166)OnAbilityFullyCast
MODIFIER_EVENT_ON_ABILITY_FULLY_CAST
--- (164)OnAbilityStart
MODIFIER_EVENT_ON_ABILITY_START
--- (157)OnAttack
MODIFIER_EVENT_ON_ATTACK
--- (177)OnAttacked
MODIFIER_EVENT_ON_ATTACKED
--- (160)OnAttackAllied
MODIFIER_EVENT_ON_ATTACK_ALLIED
--- (220)OnAttackCancelled
MODIFIER_EVENT_ON_ATTACK_CANCELLED
--- (159)OnAttackFail
MODIFIER_EVENT_ON_ATTACK_FAIL
--- (210)OnAttackFinished
MODIFIER_EVENT_ON_ATTACK_FINISHED
--- (158)OnAttackLanded
MODIFIER_EVENT_ON_ATTACK_LANDED
--- (155)OnAttackRecord
MODIFIER_EVENT_ON_ATTACK_RECORD
--- (217)OnAttackRecordDestroy
MODIFIER_EVENT_ON_ATTACK_RECORD_DESTROY
--- (156)OnAttackStart
MODIFIER_EVENT_ON_ATTACK_START
--- (167)OnBreakInvisibility
MODIFIER_EVENT_ON_BREAK_INVISIBILITY
--- (189)OnBuildingKilled
MODIFIER_EVENT_ON_BUILDING_KILLED
--- (176)OnDamageCalculated
MODIFIER_EVENT_ON_DAMAGE_CALCULATED
--- (178)OnDeath
MODIFIER_EVENT_ON_DEATH
--- (172)OnDamagePrevented
MODIFIER_EVENT_ON_DEATH_PREVENTED
--- (207)OnDominated
MODIFIER_EVENT_ON_DOMINATED
--- (184)OnHealthGained
MODIFIER_EVENT_ON_HEALTH_GAINED
--- (188)OnHealReceived
MODIFIER_EVENT_ON_HEAL_RECEIVED
--- (187)OnHeroKilled
MODIFIER_EVENT_ON_HERO_KILLED
--- (185)OnManaGained
MODIFIER_EVENT_ON_MANA_GAINED
--- (190)OnModelChanged
MODIFIER_EVENT_ON_MODEL_CHANGED
--- (191)OnModifierAdded
MODIFIER_EVENT_ON_MODIFIER_ADDED
--- (174)Unused
MODIFIER_EVENT_ON_ORB_EFFECT
--- (162)OnOrder
MODIFIER_EVENT_ON_ORDER
--- (175)OnProcessCleave
MODIFIER_EVENT_ON_PROCESS_CLEAVE
--- (169)Unused
MODIFIER_EVENT_ON_PROCESS_UPGRADE
--- (161)OnProjectileDodge
MODIFIER_EVENT_ON_PROJECTILE_DODGE
--- (218)OnProjectileObstructionHit
MODIFIER_EVENT_ON_PROJECTILE_OBSTRUCTION_HIT
--- (170)Unused
MODIFIER_EVENT_ON_REFRESH
--- (179)OnRespawn
MODIFIER_EVENT_ON_RESPAWN
--- (183)OnSetLocation
MODIFIER_EVENT_ON_SET_LOCATION
--- (154)OnSpellTargetReady
MODIFIER_EVENT_ON_SPELL_TARGET_READY
--- (180)OnSpentMana
MODIFIER_EVENT_ON_SPENT_MANA
--- (173)OnStateChanged
MODIFIER_EVENT_ON_STATE_CHANGED
--- (171)OnTakeDamage
MODIFIER_EVENT_ON_TAKEDAMAGE
--- (186)OnTakeDamageKillCredit
MODIFIER_EVENT_ON_TAKEDAMAGE_KILLCREDIT
--- (182)OnTeleported
MODIFIER_EVENT_ON_TELEPORTED
--- (181)OnTeleporting
MODIFIER_EVENT_ON_TELEPORTING
--- (163)OnUnitMoved
MODIFIER_EVENT_ON_UNIT_MOVED
--- (255)nil
MODIFIER_FUNCTION_INVALID
--- (223)nil
MODIFIER_FUNCTION_LAST
--- (206)GetModifierAbilityLayout
MODIFIER_PROPERTY_ABILITY_LAYOUT
--- (135)GetAbsoluteNoDamageMagical
MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL
--- (134)GetAbsoluteNoDamagePhysical
MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL
--- (136)GetAbsoluteNoDamagePure
MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE
--- (124)GetAbsorbSpell
MODIFIER_PROPERTY_ABSORB_SPELL
--- (145)GetAlwaysAllowAttack
MODIFIER_PROPERTY_ALWAYS_ALLOW_ATTACK
--- (146)GetAllowEtherealAttack
MODIFIER_PROPERTY_ALWAYS_ETHEREAL_ATTACK
--- (28)GetModifierAttackSpeedBaseOverride
MODIFIER_PROPERTY_ATTACKSPEED_BASE_OVERRIDE
--- (30)GetModifierAttackSpeedBonus_Constant
MODIFIER_PROPERTY_ATTACKSPEED_BONUS_CONSTANT
--- (34)GetModifierAttackPointConstant
MODIFIER_PROPERTY_ATTACK_POINT_CONSTANT
--- (94)GetModifierAttackRangeOverride
MODIFIER_PROPERTY_ATTACK_RANGE_BASE_OVERRIDE
--- (95)GetModifierAttackRangeBonus
MODIFIER_PROPERTY_ATTACK_RANGE_BONUS
--- (97)GetModifierAttackRangeBonusPercentage
MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_PERCENTAGE
--- (96)GetModifierAttackRangeBonusUnique
MODIFIER_PROPERTY_ATTACK_RANGE_BONUS_UNIQUE
--- (57)GetModifierAvoidDamage
MODIFIER_PROPERTY_AVOID_DAMAGE
--- (58)GetModifierAvoidSpell
MODIFIER_PROPERTY_AVOID_SPELL
--- (4)GetModifierBaseAttack_BonusDamage
MODIFIER_PROPERTY_BASEATTACK_BONUSDAMAGE
--- (46)GetModifierBaseDamageOutgoing_Percentage
MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE
--- (47)GetModifierBaseDamageOutgoing_PercentageUnique
MODIFIER_PROPERTY_BASEDAMAGEOUTGOING_PERCENTAGE_UNIQUE
--- (32)GetModifierBaseAttackTimeConstant
MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT
--- (33)GetModifierBaseAttackTimeConstant_Adjust
MODIFIER_PROPERTY_BASE_ATTACK_TIME_CONSTANT_ADJUST
--- (71)GetModifierBaseRegen
MODIFIER_PROPERTY_BASE_MANA_REGEN
--- (127)GetBonusDayVision
MODIFIER_PROPERTY_BONUS_DAY_VISION
--- (128)GetBonusNightVision
MODIFIER_PROPERTY_BONUS_NIGHT_VISION
--- (129)GetBonusNightVisionUnique
MODIFIER_PROPERTY_BONUS_NIGHT_VISION_UNIQUE
--- (130)GetBonusVisionPercentage
MODIFIER_PROPERTY_BONUS_VISION_PERCENTAGE
--- (222)BotAttackScoreBonus
MODIFIER_PROPERTY_BOT_ATTACK_SCORE_BONUS
--- (149)Unused
MODIFIER_PROPERTY_BOUNTY_CREEP_MULTIPLIER
--- (150)Unused
MODIFIER_PROPERTY_BOUNTY_OTHER_MULTIPLIER
--- (212)GetModifierCanAttackTrees
MODIFIER_PROPERTY_CAN_ATTACK_TREES
--- (109)GetModifierPercentageCasttime
MODIFIER_PROPERTY_CASTTIME_PERCENTAGE
--- (91)GetModifierCastRangeBonus
MODIFIER_PROPERTY_CAST_RANGE_BONUS
--- (93)GetModifierCastRangeBonusStacking
MODIFIER_PROPERTY_CAST_RANGE_BONUS_STACKING
--- (92)GetModifierCastRangeBonusTarget
MODIFIER_PROPERTY_CAST_RANGE_BONUS_TARGET
--- (205)GetModifierChangeAbilityValue
MODIFIER_PROPERTY_CHANGE_ABILITY_VALUE
--- (106)GetModifierPercentageCooldown
MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE
--- (108)GetModifierPercentageCooldownOngoing
MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_ONGOING
--- (107)GetModifierPercentageCooldownStacking
MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE_STACKING
--- (31)GetModifierCooldownReduction_Constant
MODIFIER_PROPERTY_COOLDOWN_REDUCTION_CONSTANT
--- (35)GetModifierDamageOutgoing_Percentage
MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE
--- (36)GetModifierDamageOutgoing_Percentage_Illusion
MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION
--- (37)GetModifierDamageOutgoing_Percentage_Illusion_Amplify
MODIFIER_PROPERTY_DAMAGEOUTGOING_PERCENTAGE_ILLUSION_AMPLIFY
--- (112)GetModifierConstantDeathGoldCost
MODIFIER_PROPERTY_DEATHGOLDCOST
--- (126)GetDisableAutoAttack
MODIFIER_PROPERTY_DISABLE_AUTOATTACK
--- (144)GetDisableHealing
MODIFIER_PROPERTY_DISABLE_HEALING
--- (203)GetModifierDisableTurning
MODIFIER_PROPERTY_DISABLE_TURNING
--- (152)GetModifierDodgeProjectile
MODIFIER_PROPERTY_DODGE_PROJECTILE
--- (215)GetModifierNoVisionOfAttacker
MODIFIER_PROPERTY_DONT_GIVE_VISION_OF_ATTACKER
--- (52)GetModifierEvasion_Constant
MODIFIER_PROPERTY_EVASION_CONSTANT
--- (113)GetModifierPercentageExpRateBoost
MODIFIER_PROPERTY_EXP_RATE_BOOST
--- (81)GetModifierExtraHealthBonus
MODIFIER_PROPERTY_EXTRA_HEALTH_BONUS
--- (83)GetModifierExtraHealthPercentage
MODIFIER_PROPERTY_EXTRA_HEALTH_PERCENTAGE
--- (82)GetModifierExtraManaBonus
MODIFIER_PROPERTY_EXTRA_MANA_BONUS
--- (84)GetModifierExtraManaPercentage
MODIFIER_PROPERTY_EXTRA_MANA_PERCENTAGE
--- (80)GetModifierExtraStrengthBonus
MODIFIER_PROPERTY_EXTRA_STRENGTH_BONUS
--- (29)GetModifierFixedAttackRate
MODIFIER_PROPERTY_FIXED_ATTACK_RATE
--- (131)GetFixedDayVision
MODIFIER_PROPERTY_FIXED_DAY_VISION
--- (132)GetFixedNightVision
MODIFIER_PROPERTY_FIXED_NIGHT_VISION
--- (202)GetForceDrawOnMinimap
MODIFIER_PROPERTY_FORCE_DRAW_MINIMAP
--- (78)GetModifierHealthBonus
MODIFIER_PROPERTY_HEALTH_BONUS
--- (75)GetModifierConstantHealthRegen
MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT
--- (76)GetModifierHealthRegenPercentage
MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE
--- (77)GetModifierHealthRegenPercentageUnique
MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE_UNIQUE
--- (42)GetModifierHPRegenAmplify_Percentage
MODIFIER_PROPERTY_HP_REGEN_AMPLIFY_PERCENTAGE
--- (41)GetModifierHPRegenAmplify_PercentageSource
MODIFIER_PROPERTY_HP_REGEN_AMPLIFY_PERCENTAGE_SOURCE
--- (204)GetModifierIgnoreCastAngle
MODIFIER_PROPERTY_IGNORE_CAST_ANGLE
--- (211)GetModifierIgnoreCooldown
MODIFIER_PROPERTY_IGNORE_COOLDOWN
--- (26)GetModifierIgnoreMovespeedLimit
MODIFIER_PROPERTY_IGNORE_MOVESPEED_LIMIT
--- (65)GetModifierIgnorePhysicalArmor
MODIFIER_PROPERTY_IGNORE_PHYSICAL_ARMOR
--- (138)GetModifierIllusionLabel
MODIFIER_PROPERTY_ILLUSION_LABEL
--- (214)nil
MODIFIER_PROPERTY_INCOMING_DAMAGE_ILLUSION
--- (48)GetModifierIncomingDamage_Percentage
MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE
--- (50)GetModifierIncomingPhysicalDamageConstant
MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_CONSTANT
--- (49)GetModifierIncomingPhysicalDamage_Percentage
MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE
--- (51)GetModifierIncomingSpellDamageConstant
MODIFIER_PROPERTY_INCOMING_SPELL_DAMAGE_CONSTANT
--- (12)GetModifierInvisibilityAttackBehaviorException
MODIFIER_PROPERTY_INVISIBILITY_ATTACK_BEHAVIOR_EXCEPTION
--- (11)GetModifierInvisibilityLevel
MODIFIER_PROPERTY_INVISIBILITY_LEVEL
--- (137)GetIsIllusion
MODIFIER_PROPERTY_IS_ILLUSION
--- (195)GetModifierScepter
MODIFIER_PROPERTY_IS_SCEPTER
--- (43)GetModifierLifestealRegenAmplify_Percentage
MODIFIER_PROPERTY_LIFESTEAL_AMPLIFY_PERCENTAGE
--- (199)GetUnitLifetimeFraction
MODIFIER_PROPERTY_LIFETIME_FRACTION
--- (116)GetModifierMagical_ConstantBlock
MODIFIER_PROPERTY_MAGICAL_CONSTANT_BLOCK
--- (66)GetModifierMagicalResistanceBaseReduction
MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BASE_REDUCTION
--- (68)GetModifierMagicalResistanceBonus
MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS
--- (69)GetModifierMagicalResistanceBonusIllusions
MODIFIER_PROPERTY_MAGICAL_RESISTANCE_BONUS_ILLUSIONS
--- (70)GetModifierMagicalResistanceDecrepifyUnique
MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DECREPIFY_UNIQUE
--- (67)GetModifierMagicalResistanceDirectModification
MODIFIER_PROPERTY_MAGICAL_RESISTANCE_DIRECT_MODIFICATION
--- (110)GetModifierPercentageManacost
MODIFIER_PROPERTY_MANACOST_PERCENTAGE
--- (111)GetModifierPercentageManacostStacking
MODIFIER_PROPERTY_MANACOST_PERCENTAGE_STACKING
--- (79)GetModifierManaBonus
MODIFIER_PROPERTY_MANA_BONUS
--- (72)GetModifierConstantManaRegen
MODIFIER_PROPERTY_MANA_REGEN_CONSTANT
--- (73)GetModifierConstantManaRegenUnique
MODIFIER_PROPERTY_MANA_REGEN_CONSTANT_UNIQUE
--- (74)GetModifierTotalPercentageManaRegen
MODIFIER_PROPERTY_MANA_REGEN_TOTAL_PERCENTAGE
--- (98)GetModifierMaxAttackRange
MODIFIER_PROPERTY_MAX_ATTACK_RANGE
--- (133)GetMinHealth
MODIFIER_PROPERTY_MIN_HEALTH
--- (59)GetModifierMiss_Percentage
MODIFIER_PROPERTY_MISS_PERCENTAGE
--- (193)GetModifierModelChange
MODIFIER_PROPERTY_MODEL_CHANGE
--- (194)GetModifierModelScale
MODIFIER_PROPERTY_MODEL_SCALE
--- (23)GetModifierMoveSpeed_Absolute
MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE
--- (25)GetModifierMoveSpeed_AbsoluteMax
MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MAX
--- (24)GetModifierMoveSpeed_AbsoluteMin
MODIFIER_PROPERTY_MOVESPEED_ABSOLUTE_MIN
--- (15)GetModifierMoveSpeedOverride
MODIFIER_PROPERTY_MOVESPEED_BASE_OVERRIDE
--- (14)GetModifierMoveSpeedBonus_Constant
MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT
--- (21)GetModifierMoveSpeedBonus_Constant_Unique
MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT_UNIQUE
--- (22)GetModifierMoveSpeedBonus_Constant_Unique_2
MODIFIER_PROPERTY_MOVESPEED_BONUS_CONSTANT_UNIQUE_2
--- (16)GetModifierMoveSpeedBonus_Percentage
MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE
--- (17)GetModifierMoveSpeedBonus_Percentage_Unique
MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE
--- (18)GetModifierMoveSpeedBonus_Percentage_Unique_2
MODIFIER_PROPERTY_MOVESPEED_BONUS_PERCENTAGE_UNIQUE_2
--- (19)GetModifierMoveSpeedBonus_Special_Boots
MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE
--- (20)GetModifierMoveSpeedBonus_Special_Boots_2
MODIFIER_PROPERTY_MOVESPEED_BONUS_UNIQUE_2
--- (27)GetModifierMoveSpeed_Limit
MODIFIER_PROPERTY_MOVESPEED_LIMIT
--- (44)GetModifierMPRegenAmplify_Percentage
MODIFIER_PROPERTY_MP_REGEN_AMPLIFY_PERCENTAGE
--- (45)GetModifierMPRestoreAmplify_Percentage
MODIFIER_PROPERTY_MP_RESTORE_AMPLIFY_PERCENTAGE
--- (53)GetModifierNegativeEvasion_Constant
MODIFIER_PROPERTY_NEGATIVE_EVASION_CONSTANT
--- (121)GetOverrideAnimation
MODIFIER_PROPERTY_OVERRIDE_ANIMATION
--- (123)GetOverrideAnimationRate
MODIFIER_PROPERTY_OVERRIDE_ANIMATION_RATE
--- (122)GetOverrideAnimationWeight
MODIFIER_PROPERTY_OVERRIDE_ANIMATION_WEIGHT
--- (9)GetModifierOverrideAttackDamage
MODIFIER_PROPERTY_OVERRIDE_ATTACK_DAMAGE
--- (147)GetOverrideAttackMagical
MODIFIER_PROPERTY_OVERRIDE_ATTACK_MAGICAL
--- (13)GetModifierPersistentInvisibility
MODIFIER_PROPERTY_PERSISTENT_INVISIBILITY
--- (60)GetModifierPhysicalArmorBase_Percentage
MODIFIER_PROPERTY_PHYSICAL_ARMOR_BASE_PERCENTAGE
--- (62)GetModifierPhysicalArmorBonus
MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS
--- (63)GetModifierPhysicalArmorBonusUnique
MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE
--- (64)GetModifierPhysicalArmorBonusUniqueActive
MODIFIER_PROPERTY_PHYSICAL_ARMOR_BONUS_UNIQUE_ACTIVE
--- (61)GetModifierPhysicalArmorTotal_Percentage
MODIFIER_PROPERTY_PHYSICAL_ARMOR_TOTAL_PERCENTAGE
--- (117)GetModifierPhysical_ConstantBlock
MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK
--- (118)GetModifierPhysical_ConstantBlockSpecial
MODIFIER_PROPERTY_PHYSICAL_CONSTANT_BLOCK_SPECIAL
--- (0)GetModifierPreAttack_BonusDamage
MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE
--- (3)GetModifierPreAttack_BonusDamagePostCrit
MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_POST_CRIT
--- (2)GetModifierPreAttack_BonusDamage_Proc
MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_PROC
--- (1)GetModifierPreAttack_BonusDamage_Target
MODIFIER_PROPERTY_PREATTACK_BONUS_DAMAGE_TARGET
--- (114)GetModifierPreAttack_CriticalStrike
MODIFIER_PROPERTY_PREATTACK_CRITICALSTRIKE
--- (115)GetModifierPreAttack_Target_CriticalStrike
MODIFIER_PROPERTY_PREATTACK_TARGET_CRITICALSTRIKE
--- (209)PreserveParticlesOnModelChanged
MODIFIER_PROPERTY_PRESERVE_PARTICLES_ON_MODEL_CHANGE
--- (10)GetModifierPreAttack
MODIFIER_PROPERTY_PRE_ATTACK
--- (6)GetModifierProcAttack_BonusDamage_Magical
MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL
--- (5)GetModifierProcAttack_BonusDamage_Physical
MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL
--- (7)GetModifierProcAttack_BonusDamage_Pure
MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE
--- (8)GetModifierProcAttack_Feedback
MODIFIER_PROPERTY_PROCATTACK_FEEDBACK
--- (101)GetModifierProjectileName
MODIFIER_PROPERTY_PROJECTILE_NAME
--- (99)GetModifierProjectileSpeedBonus
MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS
--- (100)GetModifierProjectileSpeedBonusPercentage
MODIFIER_PROPERTY_PROJECTILE_SPEED_BONUS_PERCENTAGE
--- (200)GetModifierProvidesFOWVision
MODIFIER_PROPERTY_PROVIDES_FOW_POSITION
--- (196)GetModifierRadarCooldownReduction
MODIFIER_PROPERTY_RADAR_COOLDOWN_REDUCTION
--- (125)GetReflectSpell
MODIFIER_PROPERTY_REFLECT_SPELL
--- (102)ReincarnateTime
MODIFIER_PROPERTY_REINCARNATION
--- (103)GetModifierConstantRespawnTime
MODIFIER_PROPERTY_RESPAWNTIME
--- (104)GetModifierPercentageRespawnTime
MODIFIER_PROPERTY_RESPAWNTIME_PERCENTAGE
--- (105)GetModifierStackingRespawnTime
MODIFIER_PROPERTY_RESPAWNTIME_STACKING
--- (201)GetModifierSpellsRequireHP
MODIFIER_PROPERTY_SPELLS_REQUIRE_HP
--- (39)GetModifierSpellAmplify_Percentage
MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE
--- (40)GetModifierSpellAmplify_PercentageUnique
MODIFIER_PROPERTY_SPELL_AMPLIFY_PERCENTAGE_UNIQUE
--- (86)GetModifierBonusStats_Agility
MODIFIER_PROPERTY_STATS_AGILITY_BONUS
--- (89)GetModifierBonusStats_Agility_Percentage
MODIFIER_PROPERTY_STATS_AGILITY_BONUS_PERCENTAGE
--- (87)GetModifierBonusStats_Intellect
MODIFIER_PROPERTY_STATS_INTELLECT_BONUS
--- (90)GetModifierBonusStats_Intellect_Percentage
MODIFIER_PROPERTY_STATS_INTELLECT_BONUS_PERCENTAGE
--- (85)GetModifierBonusStats_Strength
MODIFIER_PROPERTY_STATS_STRENGTH_BONUS
--- (88)GetModifierBonusStats_Strength_Percentage
MODIFIER_PROPERTY_STATS_STRENGTH_BONUS_PERCENTAGE
--- (54)GetModifierStatusResistance
MODIFIER_PROPERTY_STATUS_RESISTANCE
--- (56)GetModifierStatusResistanceCaster
MODIFIER_PROPERTY_STATUS_RESISTANCE_CASTER
--- (55)GetModifierStatusResistanceStacking
MODIFIER_PROPERTY_STATUS_RESISTANCE_STACKING
--- (139)GetModifierStrongIllusion
MODIFIER_PROPERTY_STRONG_ILLUSION
--- (140)GetModifierSuperIllusion
MODIFIER_PROPERTY_SUPER_ILLUSION
--- (141)GetModifierSuperIllusionWithUltimate
MODIFIER_PROPERTY_SUPER_ILLUSION_WITH_ULTIMATE
--- (221)GetSuppressCleave
MODIFIER_PROPERTY_SUPPRESS_CLEAVE
--- (219)GetSuppressTeleport
MODIFIER_PROPERTY_SUPPRESS_TELEPORT
--- (208)GetModifierTempestDouble
MODIFIER_PROPERTY_TEMPEST_DOUBLE
--- (192)OnTooltip
MODIFIER_PROPERTY_TOOLTIP
--- (216)OnTooltip2
MODIFIER_PROPERTY_TOOLTIP2
--- (38)GetModifierTotalDamageOutgoing_Percentage
MODIFIER_PROPERTY_TOTALDAMAGEOUTGOING_PERCENTAGE
--- (120)GetModifierTotal_ConstantBlock
MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK
--- (119)GetModifierPhysical_ConstantBlockUnavoidablePreArmor
MODIFIER_PROPERTY_TOTAL_CONSTANT_BLOCK_UNAVOIDABLE_PRE_ARMOR
--- (197)GetActivityTranslationModifiers
MODIFIER_PROPERTY_TRANSLATE_ACTIVITY_MODIFIERS
--- (198)GetAttackSound
MODIFIER_PROPERTY_TRANSLATE_ATTACK_SOUND
--- (153)GetTriggerCosmeticAndEndAttack
MODIFIER_PROPERTY_TRIGGER_COSMETIC_AND_END_ATTACK
--- (143)GetModifierTurnRate_Override
MODIFIER_PROPERTY_TURN_RATE_OVERRIDE
--- (142)GetModifierTurnRate_Percentage
MODIFIER_PROPERTY_TURN_RATE_PERCENTAGE
--- (151)GetModifierUnitDisllowUpgrading
MODIFIER_PROPERTY_UNIT_DISALLOW_UPGRADING
--- (148)GetModifierUnitStatsNeedsRefresh
MODIFIER_PROPERTY_UNIT_STATS_NEEDS_REFRESH
--- (213)GetVisualZDelta
MODIFIER_PROPERTY_VISUAL_Z_DELTA
